Replacing parallel comment with attribute
openrisc/or1k_marocchino pull request #17
Opened 2019-10-02 15:41 UTC by akhil-123

2019-10-02 16:28 UTC, Nancy-Chauhan commented
Thanks for the PR @akhil-123 , There are many other Verilog files which has the similar issue for example : https://github.com/openrisc/or1k_marocchino/blob/master/rtl/verilog/or1k_marocchino_ocb.v#L501

2019-10-02 16:31 UTC, Nancy-Chauhan requested changes

2019-10-02 16:31 UTC, Nancy-Chauhan commented on rtl/verilog/or1k_marocchino_bus_if_wb32.v
> +        (* parallel_case *)
Please also do similar changes at all places

2019-10-02 18:37 UTC, bandvig commented
Btw, if I remember correctly we discussed similar issue some times ago. And @olofk proposed just to move such commentaries next to `case`. Unfortunately, I could not find that discussion, but resulting commit for openrisc/mor1kx repo is:
https://github.com/openrisc/mor1kx/commit/ee7f758f4a7e0ab30488c8349c13c060a410f123 

@olofk Would it be normal for yosys to use such attributes? I would prefer to have similar style (either commentaries next to `case` or attributes before) in whole source code for MAROCCHINO.

2019-10-03 20:51 UTC, olofk commented
Yes, yosys handles this fine. The parallel_case attribute is more correct than the comment but in practice I think all tools handle both cases though. The only problem (as can be seen in the commit that @bandvig mentioned) was that yosys had problems with the comment version if it was on the line above

2019-10-03 21:04 UTC, akhil-123 commented
@bandvig @olofk If you don't use parallel_case attribute there will be no error but warnings do come that yosys doesn't support them. However when you use parallel_case attribute, then there neither warnings nor errors. So, i think when a tool is giving warning for something now, it might give error for the same in future.

2019-10-04 18:56 UTC, bandvig commented
@akhil-123 Well. I haven’t got any objection. Just one question. Have you got a plan to convert over such cases in MAROCCHINO sources? Even so you haven’t I think we could merge this and I’ll edit other such cases soon.

2019-10-11 18:10 UTC, merged